# Generated by Django 4.2.2 on 2023-09-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Профессия')),
                ('education_degree', models.CharField(max_length=200, verbose_name='Образование')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('experience_years', models.IntegerField(blank=True, null=True, verbose_name='Опыт работы')),
                ('previous_employment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предыдущее место работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/', verbose_name='Фото сотрудника')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='worker.worker')),
            ],
        ),
    ]
